# Generated by Django 5.0.2 on 2024-02-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_alter_kiralama_kiralayan_uye_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Kullanici',
        ),
    ]
