# Generated by Django 5.0.2 on 2024-02-10 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_customuser_kullanici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiralama',
            name='iha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.iha'),
        ),
        migrations.AlterField(
            model_name='kiralama',
            name='kiralayan_uye',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kullanicidetay',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
